local _, ns = ...
local addon = ns
local Utils = ns.Utils or {}
ns.Utils = Utils

local C = Utils.Constants or {}
Utils.Constants = C
addon.Constants = C

C.ADDON_VERSION = "1.1.3"
C.SCHEMA_VERSION = 3 -- NOTE: bump MAX_IMPLEMENTED_MIGRATION in savedvars.lua in sync with this value, and add the corresponding MigrateToVersion<N> function first
C.DB_NAME = "GSETrackerDB"
C.ADDON_DISPLAY_NAME = "|cFFFFFFFFGS|r|cFF00FFFFE:|r|cFFFFFF00 Tracker|r"

C.ANCHOR_CENTER = "CENTER"
C.ANCHOR_TOP = "TOP"
C.UI_PARENT_NAME = "UIParent"
C.DEFAULT_ACTION_TRACKER_POINT = { "CENTER", "UIParent", "CENTER", 0, 0 }
C.ACTION_TRACKER_POSITION_LIMIT = 3000

C.TEXTURE_WHITE8X8 = "Interface\\Buttons\\WHITE8x8"
C.MASK_CIRCLE = "Interface\\CharacterFrame\\TempPortraitAlphaMask"

C.FONT_FRIZ = "Friz Quadrata TT"
C.FONT_ARIAL_NARROW = "Arial Narrow"
C.FONT_MORPHEUS = "Morpheus"
C.FONT_SKURRI = "Skurri"
C.FONT_PATH_FRIZ = "Fonts\\FRIZQT__.TTF"
C.FONT_PATH_ARIAL_NARROW = "Fonts\\ARIALN.TTF"
C.FONT_PATH_MORPHEUS = "Fonts\\MORPHEUS.TTF"
C.FONT_PATH_SKURRI = "Fonts\\SKURRI.TTF"

C.MODE_ALWAYS = "Always"
C.MODE_IN_COMBAT = "InCombat"
C.MODE_HAS_TARGET = "HasTarget"
C.MODE_NEVER = "Never"

C.DEFAULT_SCALE = 1.00
C.DEFAULT_ICON_COUNT = 4
C.MIN_ICON_COUNT = 4
C.MAX_ICON_COUNT = 8
C.DEFAULT_ICON_GAP = 3
C.DEFAULT_BORDER_THICKNESS = 1
C.DEFAULT_PRESSED_INDICATOR_SHAPE = "dot"
C.DEFAULT_PRESSED_INDICATOR_SIZE = 10
C.PRESSED_INDICATOR_MIN_SIZE = 4
C.PRESSED_INDICATOR_MAX_SIZE = 24
C.PRESSED_INDICATOR_ACTIVE_WINDOW = 0.20

C.CLASS_FALLBACK_R = 0.20
C.CLASS_FALLBACK_G = 0.60
C.CLASS_FALLBACK_B = 1.00

C.COLOR_RED_R = 1.00
C.COLOR_RED_G = 0.20
C.COLOR_RED_B = 0.20
C.COLOR_GREEN_R = 0.20
C.COLOR_GREEN_G = 1.00
C.COLOR_GREEN_B = 0.20
C.ALPHA_SOFT = 0.10
C.ALPHA_GLOW = 0.18
C.ALPHA_DIM = 0.60
C.ALPHA_DEFAULT = 0.90
C.ALPHA_STRONG = 0.95

C.ACTION_TRACKER_MARKER_BASE_SIZE = 48
C.ACTION_TRACKER_MARKER_MIN_SIZE = 8
C.ACTION_TRACKER_MARKER_GLOW_INSET = 6
C.ACTION_TRACKER_MARKER_CROSS_THICKNESS = 2
C.ACTION_TRACKER_MARKER_FRAME_LEVEL = 50
C.STRATA_MEDIUM = "MEDIUM"
C.STRATA_TOOLTIP = "TOOLTIP"
C.DEFAULT_COMBAT_TRACKER_STRATA = C.STRATA_MEDIUM
C.VALID_FRAME_STRATA = { BACKGROUND = true, LOW = true, MEDIUM = true, HIGH = true, DIALOG = true, FULLSCREEN = true, FULLSCREEN_DIALOG = true, TOOLTIP = true }

C.COMBAT_MARKER_MIN_SIZE = 16
C.COMBAT_MARKER_MAX_SIZE = 128
C.COMBAT_MARKER_DEFAULT_SIZE = 40
C.COMBAT_MARKER_DEFAULT_ALPHA = 0.85
C.ASSISTED_HIGHLIGHT_DEFAULT_ALPHA = 1.00
C.COMBAT_MARKER_DEFAULT_SYMBOL = "x"
C.COMBAT_MARKER_DEFAULT_POINT = { "CENTER", "UIParent", "CENTER", 0, 120 }
C.COMBAT_MARKER_DEFAULT_SHOW_WHEN = C.MODE_IN_COMBAT
C.COMBAT_MARKER_DEFAULT_THICKNESS = 4
C.COMBAT_MARKER_MIN_THICKNESS = 1
C.COMBAT_MARKER_MAX_THICKNESS = 12
C.COMBAT_MARKER_DEFAULT_BORDER_SIZE = 2
C.COMBAT_MARKER_MIN_BORDER_SIZE = 0
C.COMBAT_MARKER_MAX_BORDER_SIZE = 8
C.COMBAT_MARKER_POSITION_LIMIT = C.ACTION_TRACKER_POSITION_LIMIT
C.COMBAT_MARKER_VALID_ANCHORS = {
  CENTER = true,
  TOP = true,
  BOTTOM = true,
  LEFT = true,
  RIGHT = true,
  TOPLEFT = true,
  TOPRIGHT = true,
  BOTTOMLEFT = true,
  BOTTOMRIGHT = true,
}

function C:CopyDefaultActionTrackerPoint()
  local p = self.DEFAULT_ACTION_TRACKER_POINT
  return { p[1], p[2], p[3], p[4], p[5] }
end
